export const cabinsContent = {
    en: {
        'historic-cabin': { name: 'Historic Cabin', tagline: 'An Art Deco Masterpiece', description: 'The original 1920s cabins, restored to their former glory. By day, a comfortable lounge; by night, a cozy bedroom with upper and lower berths.', price: 'From £3,530 per passenger', features: ['Convertible sofa-bed', 'Washbasin with hot/cold water', 'Complimentary bathrobes', '24-hour steward service'] },
        'suite': { name: 'Suite', tagline: 'Modern Comfort, Vintage Style', description: 'New for 2023, these suites offer increased space and a private marble en-suite, bridging the gap between Historic Cabins and Grand Suites.', price: 'From £7,200 per passenger', features: ['Double or twin beds', 'Private en-suite bathroom', 'Complimentary champagne', 'Daytime lounge configuration'] },
        'grand-suite': { name: 'Grand Suite', tagline: 'The Ultimate Indulgence', description: 'The most spacious and opulent accommodation on board. Each Grand Suite is unique, named after the cities the train visits (Paris, Venice, Istanbul).', price: 'From £10,100 per passenger', features: ['Private in-suite dining', 'Unlimited champagne', 'Mosaic en-suite', '24-hour butler service'] }
    },
    fr: {
        'historic-cabin': { name: 'Cabine Historique', tagline: 'Un Chef-d\'œuvre Art Déco', description: 'Les cabines originales des années 1920, restaurées dans leur ancienne gloire. Le jour, un salon confortable ; la nuit, une chambre douillette avec lits superposés.', price: 'Dès 3 530 £ par passager', features: ['Canapé-lit convertible', 'Lavabo avec eau chaude/froide', 'Peignoirs offerts', 'Service de steward 24h/24'] },
        'suite': { name: 'Suite', tagline: 'Confort Moderne, Style Vintage', description: 'Nouveauté 2023, ces suites offrent plus d\'espace et une salle de bain privée en marbre, faisant le lien entre les cabines historiques et les grandes suites.', price: 'Dès 7 200 £ par passager', features: ['Lits doubles ou jumeaux', 'Salle de bain privée', 'Champagne offert', 'Configuration salon en journée'] },
        'grand-suite': { name: 'Grande Suite', tagline: 'L\'Indulgence Ultime', description: 'L\'hébergement le plus spacieux et le plus opulent à bord. Chaque Grande Suite est unique, portant le nom des villes que le train traverse (Paris, Venise, Istanbul).', price: 'Dès 10 100 £ par passager', features: ['Dîner privé en suite', 'Champagne à volonté', 'Salle de bain en mosaïque', 'Majordome 24h/24'] }
    },
    it: {
        'historic-cabin': { name: 'Cabina Storica', tagline: 'Un Capolavoro Art Déco', description: 'Le cabine originali degli anni \'20, restaurate al loro antico splendore. Di giorno, un comodo salotto; di notte, un\'accogliente camera da letto con cuccette superiori e inferiori.', price: 'Da £ 3.530 per passeggero', features: ['Divano letto convertibile', 'Lavabo con acqua calda/fredda', 'Accappatoi gratuiti', 'Servizio steward 24 ore su 24'] },
        'suite': { name: 'Suite', tagline: 'Comfort Moderno, Stile Vintage', description: 'Novità del 2023, queste suite offrono maggiore spazio e un bagno privato in marmo, colmando il divario tra le cabine storiche e le Grand Suite.', price: 'Da £ 7.200 per passeggero', features: ['Letti matrimoniali o singoli', 'Bagno privato in camera', 'Champagne in omaggio', 'Configurazione lounge diurna'] },
        'grand-suite': { name: 'Grand Suite', tagline: 'Il Massimo Piacere', description: 'La sistemazione più spaziosa e opulenta a bordo. Ogni Grand Suite è unica e prende il nome dalle città visitate dal treno (Parigi, Venezia, Istanbul).', price: 'Da £ 10.100 per passeggero', features: ['Cena privata in suite', 'Champagne illimitato', 'Bagno in mosaico', 'Servizio maggiordomo 24 ore su 24'] }
    },
    de: {
        'historic-cabin': { name: 'Historische Kabine', tagline: 'Ein Art-déco-Meisterwerk', description: 'Die originalen Kabinen aus den 1920er Jahren, in ihrer alten Pracht restauriert. Tagsüber ein bequemer Aufenthaltsraum; nachts ein gemütliches Schlafzimmer mit oberem und unterem Bett.', price: 'Ab 3.530 £ pro Passagier', features: ['Umbau-Sofabett', 'Waschbecken mit Warm-/Kaltwasser', 'Kostenlose Bademäntel', '24-Stunden-Steward-Service'] },
        'suite': { name: 'Suite', tagline: 'Moderner Komfort, Vintage-Stil', description: 'Neu für 2023. Diese Suiten bieten mehr Platz und ein eigenes Marmorbad und schließen die Lücke zwischen historischen Kabinen und Grand Suiten.', price: 'Ab 7.200 £ pro Passagier', features: ['Doppel- oder Einzelbetten', 'Eigenes Badezimmer', 'Kostenloser Champagner', 'Tages-Lounge-Konfiguration'] },
        'grand-suite': { name: 'Grand Suite', tagline: 'Der höchste Genuss', description: 'Die geräumigste und opulenteste Unterkunft an Bord. Jede Grand Suite ist einzigartig und nach den Städten benannt, die der Zug besucht (Paris, Venedig, Istanbul).', price: 'Ab 10.100 £ pro Passagier', features: ['Privates Essen', 'Unbegrenzter Champagner', 'Mosaik-Badezimmer', '24-Stunden-Butler-Service'] }
    }
};
