type DictionaryContent = {
    nav: { destinations: string; experiences: string; packages: string; suites: string; occasions: string; offers: string; membership: string; stories: string; myBookings: string; search: string; bookJourney: string; book: string; };
    hero: { title: string; subtitleDefault: string; subtitleGastronomy: string; };
    ai: { greeting: string; };
    map: { londonDesc: string; parisDesc: string; veniceDesc: string; istanbulDesc: string; grandTour: string; discover: string; selectRoute: string; network: string; };
    history: { legend: string; title1: string; title2: string; desc: string; restored: string; restoredSub: string; era: string; eraSub: string; discover: string; };
    marquee: { vsoe: string; cities: string; art: string; };
    routes: { duration: string; dates: string; reserve: string; journey1Title: string; journey1Route: string; journey1Duration: string; journey1Desc: string; journey1Price: string; journey1Dates: string; journey2Title: string; journey2Route: string; journey2Duration: string; journey2Desc: string; journey2Price: string; journey2Dates: string; journey3Title: string; journey3Route: string; journey3Duration: string; journey3Desc: string; journey3Price: string; journey3Dates: string; };
    suites: { title: string; sub: string; suite1City: string; suite1Desc: string; suite1Feat1: string; suite1Feat2: string; suite1Feat3: string; suite2City: string; suite2Desc: string; suite2Feat1: string; suite2Feat2: string; suite2Feat3: string; suite3City: string; suite3Desc: string; suite3Feat1: string; suite3Feat2: string; suite3Feat3: string; };
    dining: { gastronomy: string; haute: string; desc: string; sommelier: string; michelin: string; view: string; };
    journal: { narrative: string; fromJournal: string; read: string; article1: string; article2: string; article3: string; };
    footer: { join: string; newsletter: string; subscribe: string; follow: string; about: string; story: string; careers: string; press: string; sustainability: string; support: string; contact: string; faqs: string; gifts: string; legal: string; privacy: string; cookies: string; terms: string; accessibility: string; language: string; copyright: string; lvmh: string; sitemap: string; };
};

export const dictionaries: Record<string, DictionaryContent> = {
    EN: {
        nav: { destinations: 'Destinations', experiences: 'Experiences', packages: 'Packages & Tours', suites: 'Signature Suites', occasions: 'Occasions', offers: 'Offers', membership: 'Membership', stories: 'Stories', myBookings: 'My Bookings', search: 'Search', bookJourney: 'Book a Journey', book: 'Book' },
        hero: { title: 'Venice Simplon-Orient-Express', subtitleDefault: 'Beyond the Golden Age', subtitleGastronomy: 'Taste the Extraordinary' },
        ai: { greeting: "Good evening. I am Vitesse, your personal concierge. How may I assist you with your journey today?" },
        map: { londonDesc: 'The Departure', parisDesc: 'City of Light', veniceDesc: 'The Arrival', istanbulDesc: 'The Gateway', grandTour: 'European Grand Tour', discover: 'Discover Journey', selectRoute: 'SELECT A ROUTE', network: 'Venice Simplon-Orient-Express Network' },
        history: { legend: 'The Legend', title1: 'Art Deco', title2: 'Masterpiece', desc: 'Step into a world where time stands still. The Venice Simplon-Orient-Express is not merely a train, but a rolling museum of 1920s elegance. Each carriage has been lovingly restored by expert craftsmen to its original glory, featuring intricate marquetry, polished brass, and sumptuous upholstery.', restored: '17', restoredSub: 'Restored Carriages', era: '1920s', eraSub: 'Original Era', discover: 'Discover' },
        marquee: { vsoe: 'Venice Simplon-Orient-Express', cities: 'London • Paris • Venice • Istanbul', art: 'The Art of Belmond' },
        routes: { duration: 'Duration', dates: 'Dates', reserve: 'Reserve', journey1Title: 'The Classic Route', journey1Route: 'Paris → Venice', journey1Duration: '1 Night', journey1Desc: 'The original journey. Depart Paris in the late afternoon and awake to the scenery of the Swiss Alps.', journey1Price: 'From £3,530', journey1Dates: 'Mar 2025 - Nov 2025', journey2Title: 'The Gateway', journey2Route: 'Paris → Istanbul', journey2Duration: '5 Nights', journey2Desc: 'A historic transcontinental odyssey. Only runs once a year in late August.', journey2Price: 'From £17,500', journey2Dates: 'August 2025 Only', journey3Title: 'The Italian', journey3Route: 'Venice → Paris', journey3Duration: '1 Night', journey3Desc: 'Return from the floating city in style. Brunch in the Dolomites, tea in France.', journey3Price: 'From £3,530', journey3Dates: 'Mar 2025 - Nov 2025' },
        suites: { title: 'The Grand Suites', sub: 'A World of Their Own', suite1City: 'Paris', suite1Desc: 'Light and sophisticated, reflecting the city’s haute couture and gastronomic excellence.', suite1Feat1: 'Private en-suite bathroom', suite1Feat2: '24-hour butler service', suite1Feat3: 'Free-flowing champagne', suite2City: 'Venice', suite2Desc: 'Grandeur and romance, adorned with Venetian silk, woven fabrics and glass lamps.', suite2Feat1: 'Murano glass details', suite2Feat2: 'Hand-crafted marquetry', suite2Feat3: 'Living area', suite3City: 'Istanbul', suite3Desc: 'Exotic and opulent, inspired by the Grand Bazaar and Ottoman architecture.', suite3Feat1: 'Hand-carved timber', suite3Feat2: 'Embroidered pillows', suite3Feat3: 'Mosaic en-suite' },
        dining: { gastronomy: 'Gastronomy', haute: 'Haute Cuisine', desc: 'Local, seasonal produce is taken on board at stops along the route. From Brittany lobsters to salt marsh lamb, every meal is an event in itself.', sommelier: 'Sommelier Service', michelin: 'Michelin Chefs', view: 'View Menus' },
        journal: { narrative: 'The Narrative', fromJournal: 'From The Journal', read: 'Read the Journal', article1: 'The Art of Slow Travel', article2: 'Culinary Masterpieces', article3: 'Restoring a Legend' },
        footer: { join: 'Join our world', newsletter: 'Sign up for our newsletter to receive exclusive offers, travel inspiration, and the latest news from Belmond.', subscribe: 'Subscribe', follow: 'Follow us', about: 'About Belmond', story: 'Our Story', careers: 'Careers', press: 'Press & Media', sustainability: 'Sustainability', support: 'Support', contact: 'Contact Us', faqs: 'FAQs', gifts: 'Gift Cards', legal: 'Legal', privacy: 'Privacy Policy', cookies: 'Cookie Policy', terms: 'Terms & Conditions', accessibility: 'Accessibility', language: 'Language', copyright: '© 2025 Belmond Management Limited', lvmh: 'LVMH Maisons', sitemap: 'Sitemap' }
    },
    FR: {
        nav: { destinations: 'Destinations', experiences: 'Expériences', packages: 'Forfaits', suites: 'Suites Signature', occasions: 'Événements', offers: 'Offres', membership: 'Adhésion', stories: 'Récits', myBookings: 'Mes Réservations', search: 'Recherche', bookJourney: 'Réserver', book: 'Réserver' },
        hero: { title: 'Venise Simplon-Orient-Express', subtitleDefault: "Au-delà de l'âge d'or", subtitleGastronomy: "Goûtez à l'extraordinaire" },
        ai: { greeting: "Bonsoir. Je suis Vitesse, votre concierge personnel. Comment puis-je vous aider dans votre voyage aujourd'hui ?" },
        map: { londonDesc: 'Le Départ', parisDesc: 'Ville Lumière', veniceDesc: 'L\'Arrivée', istanbulDesc: 'La Passerelle', grandTour: 'Grand Tour Européen', discover: 'Découvrir le Voyage', selectRoute: 'SÉLECTIONNER UN ITINÉRAIRE', network: 'Réseau Venice Simplon-Orient-Express' },
        history: { legend: 'La Légende', title1: 'Chef-d\'œuvre', title2: 'Art Déco', desc: 'Entrez dans un monde où le temps s\'arrête. Le Venice Simplon-Orient-Express n\'est pas seulement un train, mais un musée roulant de l\'élégance des années 1920. Chaque voiture a été restaurée avec amour par des artisans experts.', restored: '17', restoredSub: 'Voitures Restaurées', era: 'Années 20', eraSub: 'Époque d\'Origine', discover: 'Découvrir' },
        marquee: { vsoe: 'Venise Simplon-Orient-Express', cities: 'Londres • Paris • Venise • Istanbul', art: 'L\'Art de Belmond' },
        routes: { duration: 'Durée', dates: 'Dates', reserve: 'Réserver', journey1Title: 'L\'Itinéraire Classique', journey1Route: 'Paris → Venise', journey1Duration: '1 Nuit', journey1Desc: 'Le voyage original. Partez de Paris en fin d\'après-midi et réveillez-vous avec le paysage des Alpes suisses.', journey1Price: 'Dès 3 530 £', journey1Dates: 'Mars 2025 - Nov 2025', journey2Title: 'La Passerelle', journey2Route: 'Paris → Istanbul', journey2Duration: '5 Nuits', journey2Desc: 'Une odyssée transcontinentale historique. Une seule fois par an fin août.', journey2Price: 'Dès 17 500 £', journey2Dates: 'Août 2025 Uniquement', journey3Title: 'L\'Italien', journey3Route: 'Venise → Paris', journey3Duration: '1 Nuit', journey3Desc: 'Revenez de la cité flottante avec style. Brunch dans les Dolomites, thé en France.', journey3Price: 'Dès 3 530 £', journey3Dates: 'Mars 2025 - Nov 2025' },
        suites: { title: 'Les Grandes Suites', sub: 'Un Monde à Part', suite1City: 'Paris', suite1Desc: 'Lumière et sophistication, reflétant la haute couture et l\'excellence gastronomique de la ville.', suite1Feat1: 'Salle de bain privée attenante', suite1Feat2: 'Service de majordome 24h/24', suite1Feat3: 'Champagne à volonté', suite2City: 'Venise', suite2Desc: 'Grandeur et romance, ornées de soie vénitienne, de tissus tissés et de lampes en verre.', suite2Feat1: 'Détails en verre de Murano', suite2Feat2: 'Marqueterie artisanale', suite2Feat3: 'Espace salon', suite3City: 'Istanbul', suite3Desc: 'Exotique et opulente, inspirée du Grand Bazar et de l\'architecture ottomane.', suite3Feat1: 'Bois sculpté à la main', suite3Feat2: 'Coussins brodés', suite3Feat3: 'Salle de bain en mosaïque' },
        dining: { gastronomy: 'Gastronomie', haute: 'Haute Cuisine', desc: 'Des produits locaux et de saison sont embarqués lors des arrêts en cours de route. Du homard breton à l\'agneau de pré-salé, chaque repas est un événement en soi.', sommelier: 'Service Sommelier', michelin: 'Chefs Étoilés', view: 'Voir les Menus' },
        journal: { narrative: 'Le Récit', fromJournal: 'Extrait du Journal', read: 'Lire le Journal', article1: 'L\'Art du Voyage Lent', article2: 'Chefs-d\'œuvre Culinaires', article3: 'Restauration d\'une Légende' },
        footer: { join: 'Rejoignez notre monde', newsletter: 'Inscrivez-vous à notre newsletter pour recevoir des offres exclusives, de l\'inspiration et les dernières nouvelles.', subscribe: 'S\'abonner', follow: 'Suivez-nous', about: 'À propos de Belmond', story: 'Notre Histoire', careers: 'Carrières', press: 'Presse et Médias', sustainability: 'Développement Durable', support: 'Assistance', contact: 'Nous Contacter', faqs: 'FAQ', gifts: 'Cartes Cadeaux', legal: 'Légal', privacy: 'Politique de Confidentialité', cookies: 'Politique des Cookies', terms: 'Conditions Générales', accessibility: 'Accessibilité', language: 'Langue', copyright: '© 2025 Belmond Management Limited', lvmh: 'Maisons LVMH', sitemap: 'Plan du site' }
    },
    IT: {
        nav: { destinations: 'Destinazioni', experiences: 'Esperienze', packages: 'Pacchetti', suites: 'Suite Esclusive', occasions: 'Occasioni', offers: 'Offerte', membership: 'Iscrizione', stories: 'Storie', myBookings: 'Prenotazioni', search: 'Cerca', bookJourney: 'Prenota un viaggio', book: 'Prenota' },
        hero: { title: 'Venice Simplon-Orient-Express', subtitleDefault: "Oltre l'età dell'oro", subtitleGastronomy: "Assapora lo straordinario" },
        ai: { greeting: "Buonasera. Sono Vitesse, il suo concierge personale. Come posso assisterla nel suo viaggio oggi?" },
        map: { londonDesc: 'La Partenza', parisDesc: 'Città della Luce', veniceDesc: 'L\'Arrivo', istanbulDesc: 'La Porta', grandTour: 'Grand Tour Europeo', discover: 'Scopri il Viaggio', selectRoute: 'SELEZIONA UN PERCORSO', network: 'Rete Venice Simplon-Orient-Express' },
        history: { legend: 'La Leggenda', title1: 'Capolavoro', title2: 'Art Déco', desc: 'Entra in un mondo in cui il tempo si ferma. Il Venice Simplon-Orient-Express non è solo un treno, ma un museo su rotaie dell\'eleganza degli anni \'20. Ogni carrozza è stata amorevolmente restaurata da esperti artigiani.', restored: '17', restoredSub: 'Carrozze Restaurate', era: 'Anni 20', eraSub: 'Epoca Originale', discover: 'Scoprire' },
        marquee: { vsoe: 'Venice Simplon-Orient-Express', cities: 'Londra • Parigi • Venezia • Istanbul', art: 'L\'Arte di Belmond' },
        routes: { duration: 'Durata', dates: 'Date', reserve: 'Prenota', journey1Title: 'Il Percorso Classico', journey1Route: 'Parigi → Venezia', journey1Duration: '1 Notte', journey1Desc: 'Il viaggio originale. Parti da Parigi nel tardo pomeriggio e svegliati con lo scenario delle Alpi svizzere.', journey1Price: 'Da £ 3.530', journey1Dates: 'Mar 2025 - Nov 2025', journey2Title: 'La Porta', journey2Route: 'Parigi → Istanbul', journey2Duration: '5 Notti', journey2Desc: 'Una storica odissea transcontinentale. Si effettua solo una volta all\'anno a fine agosto.', journey2Price: 'Da £ 17.500', journey2Dates: 'Solo Agosto 2025', journey3Title: 'L\'Italiano', journey3Route: 'Venezia → Parigi', journey3Duration: '1 Notte', journey3Desc: 'Ritorna dalla città galleggiante con stile. Brunch sulle Dolomiti, tè in Francia.', journey3Price: 'Da £ 3.530', journey3Dates: 'Mar 2025 - Nov 2025' },
        suites: { title: 'Le Grand Suites', sub: 'Un Mondo a Parte', suite1City: 'Parigi', suite1Desc: 'Luce e raffinatezza, che riflettono l\'alta moda e l\'eccellenza gastronomica della città.', suite1Feat1: 'Bagno privato in camera', suite1Feat2: 'Servizio maggiordomo 24h', suite1Feat3: 'Champagne illimitato', suite2City: 'Venezia', suite2Desc: 'Grandezza e romanticismo, adornati con seta veneziana, tessuti e lampade in vetro.', suite2Feat1: 'Dettagli in vetro di Murano', suite2Feat2: 'Intarsio artigianale', suite2Feat3: 'Zona giorno', suite3City: 'Istanbul', suite3Desc: 'Esotico e opulento, ispirato al Grand Bazaar e all\'architettura ottomana.', suite3Feat1: 'Legno intagliato a mano', suite3Feat2: 'Cuscini ricamati', suite3Feat3: 'Bagno in mosaico' },
        dining: { gastronomy: 'Gastronomia', haute: 'Alta Cucina', desc: 'Prodotti locali e di stagione vengono caricati a bordo durante le fermate lungo il percorso. Dall\'aragosta bretone all\'agnello di palude, ogni pasto è un evento in sé.', sommelier: 'Servizio Sommelier', michelin: 'Chef Stellati', view: 'Vedi i Menu' },
        journal: { narrative: 'La Narrazione', fromJournal: 'Dal Diario', read: 'Leggi il Diario', article1: 'L\'Arte del Viaggio Lento', article2: 'Capolavori Culinari', article3: 'Restaurare una Leggenda' },
        footer: { join: 'Entra nel nostro mondo', newsletter: 'Iscriviti alla nostra newsletter per ricevere offerte esclusive, ispirazione di viaggio e le ultime notizie.', subscribe: 'Iscriviti', follow: 'Seguici', about: 'Informazioni su Belmond', story: 'La Nostra Storia', careers: 'Lavora con noi', press: 'Stampa e Media', sustainability: 'Sostenibilità', support: 'Supporto', contact: 'Contattaci', faqs: 'Domande Frequenti', gifts: 'Carte Regalo', legal: 'Legale', privacy: 'Informativa sulla Privacy', cookies: 'Informativa sui Cookie', terms: 'Termini e Condizioni', accessibility: 'Accessibilità', language: 'Lingua', copyright: '© 2025 Belmond Management Limited', lvmh: 'LVMH Maisons', sitemap: 'Mappa del sito' }
    },
    DE: {
        nav: { destinations: 'Reiseziele', experiences: 'Erlebnisse', packages: 'Pakete', suites: 'Suiten', occasions: 'Anlässe', offers: 'Angebote', membership: 'Mitgliedschaft', stories: 'Geschichten', myBookings: 'Buchungen', search: 'Suche', bookJourney: 'Reise buchen', book: 'Buchen' },
        hero: { title: 'Venice Simplon-Orient-Express', subtitleDefault: 'Jenseits des goldenen Zeitalters', subtitleGastronomy: 'Schmecken Sie das Außergewöhnliche' },
        ai: { greeting: "Guten Abend. Ich bin Vitesse, Ihr persönlicher Concierge. Wie kann ich Ihnen heute bei Ihrer Reise behilflich sein?" },
        map: { londonDesc: 'Die Abfahrt', parisDesc: 'Stadt des Lichts', veniceDesc: 'Die Ankunft', istanbulDesc: 'Das Tor', grandTour: 'Europäische Grand Tour', discover: 'Reise Entdecken', selectRoute: 'ROUTE WÄHLEN', network: 'Venice Simplon-Orient-Express Netzwerk' },
        history: { legend: 'Die Legende', title1: 'Art-déco-', title2: 'Meisterwerk', desc: 'Treten Sie ein in eine Welt, in der die Zeit stillsteht. Der Venice Simplon-Orient-Express ist nicht nur ein Zug, sondern ein rollendes Museum der Eleganz der 1920er Jahre. Jeder Wagen wurde von erfahrenen Handwerkern liebevoll restauriert.', restored: '17', restoredSub: 'Restaurierte Wagen', era: '1920er', eraSub: 'Original-Ära', discover: 'Entdecken' },
        marquee: { vsoe: 'Venice Simplon-Orient-Express', cities: 'London • Paris • Venedig • Istanbul', art: 'Die Kunst von Belmond' },
        routes: { duration: 'Dauer', dates: 'Daten', reserve: 'Reservieren', journey1Title: 'Die Klassische Route', journey1Route: 'Paris → Venedig', journey1Duration: '1 Nacht', journey1Desc: 'Die ursprüngliche Reise. Verlassen Sie Paris am späten Nachmittag und erwachen Sie mit der Landschaft der Schweizer Alpen.', journey1Price: 'Ab 3.530 £', journey1Dates: 'Mär 2025 - Nov 2025', journey2Title: 'Das Tor', journey2Route: 'Paris → Istanbul', journey2Duration: '5 Nächte', journey2Desc: 'Eine historische transkontinentale Odyssee. Fährt nur einmal im Jahr Ende August.', journey2Price: 'Ab 17.500 £', journey2Dates: 'Nur August 2025', journey3Title: 'Der Italiener', journey3Route: 'Venedig → Paris', journey3Duration: '1 Nacht', journey3Desc: 'Rückkehr aus der schwimmenden Stadt mit Stil. Brunch in den Dolomiten, Tee in Frankreich.', journey3Price: 'Ab 3.530 £', journey3Dates: 'Mär 2025 - Nov 2025' },
        suites: { title: 'Die Grand Suiten', sub: 'Eine Welt für sich', suite1City: 'Paris', suite1Desc: 'Leicht und raffiniert, spiegelt die Haute Couture und gastronomische Exzellenz der Stadt wider.', suite1Feat1: 'Eigenes Badezimmer', suite1Feat2: '24-Stunden-Butler-Service', suite1Feat3: 'Champagner ohne Ende', suite2City: 'Venedig', suite2Desc: 'Größe und Romantik, geschmückt mit venezianischer Seide, gewebten Stoffen und Glaslampen.', suite2Feat1: 'Murano-Glasdetails', suite2Feat2: 'Handgefertigte Intarsien', suite2Feat3: 'Wohnbereich', suite3City: 'Istanbul', suite3Desc: 'Exotisch und opulent, inspiriert vom Großen Basar und der osmanischen Architektur.', suite3Feat1: 'Handgeschnitztes Holz', suite3Feat2: 'Bestickte Kissen', suite3Feat3: 'Mosaik-Badezimmer' },
        dining: { gastronomy: 'Gastronomie', haute: 'Haute Cuisine', desc: 'Lokale, saisonale Produkte werden an Haltestellen entlang der Route an Bord genommen. Vom bretonischen Hummer bis zum Salzwiesenlamm ist jede Mahlzeit ein Ereignis für sich.', sommelier: 'Sommelier-Service', michelin: 'Sterneköche', view: 'Menüs Ansehen' },
        journal: { narrative: 'Die Erzählung', fromJournal: 'Aus dem Journal', read: 'Journal Lesen', article1: 'Die Kunst des langsamen Reisens', article2: 'Kulinarische Meisterwerke', article3: 'Eine Legende restaurieren' },
        footer: { join: 'Treten Sie unserer Welt bei', newsletter: 'Melden Sie sich für unseren Newsletter an, um exklusive Angebote, Reiseinspirationen und die neuesten Nachrichten zu erhalten.', subscribe: 'Abonnieren', follow: 'Folgen Sie uns', about: 'Über Belmond', story: 'Unsere Geschichte', careers: 'Karriere', press: 'Presse & Medien', sustainability: 'Nachhaltigkeit', support: 'Unterstützung', contact: 'Kontakt', faqs: 'Häufig gestellte Fragen', gifts: 'Geschenkkarten', legal: 'Rechtliches', privacy: 'Datenschutzrichtlinie', cookies: 'Cookie-Richtlinie', terms: 'Geschäftsbedingungen', accessibility: 'Barrierefreiheit', language: 'Sprache', copyright: '© 2025 Belmond Management Limited', lvmh: 'LVMH Maisons', sitemap: 'Seitenverzeichnis' }
    }
};
